//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarLeasePPT.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthenticationFailure
    {
        public int PersonId { get; set; }
        public int FailureSequence { get; set; }
        public System.DateTime LastFailure { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
