//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarLeasePPT.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParcelTaxBill
    {
        public int ParcelTaxBillId { get; set; }
        public int ParcelId { get; set; }
        public int TaxBillId { get; set; }
        public System.DateTime CreatedOnDateTime { get; set; }
    
        public virtual Parcel Parcel { get; set; }
        public virtual TaxBill TaxBill { get; set; }
    }
}
