//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarLeasePPT.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.AuditLogsCreatedBy = new HashSet<AuditLog>();
            this.AuditLogsReviewedBy = new HashSet<AuditLog>();
            this.PersonRoles = new HashSet<PersonRole>();
            this.PersonSecurityResets = new HashSet<PersonSecurityReset>();
            this.PersonSecurities = new HashSet<PersonSecurity>();
            this.PersonSecuritiesCreatedBy = new HashSet<PersonSecurity>();
            this.PersonSecuritiesModifiedBy = new HashSet<PersonSecurity>();
            this.PersonBlocks = new HashSet<PersonBlock>();
            this.PersonBlocksOverriddenBy = new HashSet<PersonBlock>();
            this.WorkItemsCreatedBy = new HashSet<WorkItem>();
            this.WorkItemsModifiedBy = new HashSet<WorkItem>();
            this.LeaseAttachmentsCreatedBy = new HashSet<LeaseAttachment>();
            this.LeaseAttachmentsDeletedBy = new HashSet<LeaseAttachment>();
            this.LeaseAttachmentsModifiedBy = new HashSet<LeaseAttachment>();
            this.TaxBillAttachmentsCreatedBy = new HashSet<TaxBillAttachment>();
            this.TaxBillAttachmentsDeletedBy = new HashSet<TaxBillAttachment>();
            this.TaxBillAttachmentsModifiedBy = new HashSet<TaxBillAttachment>();
            this.WorkItemActivitiesCreatedBy = new HashSet<WorkItemActivity>();
            this.WorkItemActivitiesDeletedBy = new HashSet<WorkItemActivity>();
            this.WorkItemAttachmentsCreatedBy = new HashSet<WorkItemAttachment>();
            this.WorkItemAttachmentsDeletedBy = new HashSet<WorkItemAttachment>();
            this.WorkItemAttachmentsModifiedBy = new HashSet<WorkItemAttachment>();
            this.TaxAssessorsCreatedBy = new HashSet<TaxAssessor>();
            this.TaxAssessorsDeletedBy = new HashSet<TaxAssessor>();
            this.TaxAssessorsModifiedBy = new HashSet<TaxAssessor>();
            this.TaxCollectorsCreatedBy = new HashSet<TaxCollector>();
            this.TaxCollectorsDeletedBy = new HashSet<TaxCollector>();
            this.TaxCollectorsModifiedBy = new HashSet<TaxCollector>();
        }
    
        public int PersonId { get; set; }
        public string FullName { get; set; }
        public string PreferredName { get; set; }
        public string EmailAddress { get; set; }
        public bool IsLocked { get; set; }
        public bool IsExpired { get; set; }
        public System.DateTime EffectiveDateTime { get; set; }
        public Nullable<System.DateTime> ExpirationDateTime { get; set; }
        public int ModifiedByPersonId { get; set; }
        public System.DateTime ModifiedOnDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditLog> AuditLogsCreatedBy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditLog> AuditLogsReviewedBy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonRole> PersonRoles { get; set; }
        public virtual PersonSession PersonSession { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonSecurityReset> PersonSecurityResets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonSecurity> PersonSecurities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonSecurity> PersonSecuritiesCreatedBy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonSecurity> PersonSecuritiesModifiedBy { get; set; }
        public virtual AuthenticationFailure AuthenticationFailure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonBlock> PersonBlocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonBlock> PersonBlocksOverriddenBy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkItem> WorkItemsCreatedBy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkItem> WorkItemsModifiedBy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaseAttachment> LeaseAttachmentsCreatedBy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaseAttachment> LeaseAttachmentsDeletedBy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaseAttachment> LeaseAttachmentsModifiedBy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaxBillAttachment> TaxBillAttachmentsCreatedBy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaxBillAttachment> TaxBillAttachmentsDeletedBy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaxBillAttachment> TaxBillAttachmentsModifiedBy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkItemActivity> WorkItemActivitiesCreatedBy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkItemActivity> WorkItemActivitiesDeletedBy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkItemAttachment> WorkItemAttachmentsCreatedBy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkItemAttachment> WorkItemAttachmentsDeletedBy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkItemAttachment> WorkItemAttachmentsModifiedBy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaxAssessor> TaxAssessorsCreatedBy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaxAssessor> TaxAssessorsDeletedBy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaxAssessor> TaxAssessorsModifiedBy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaxCollector> TaxCollectorsCreatedBy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaxCollector> TaxCollectorsDeletedBy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaxCollector> TaxCollectorsModifiedBy { get; set; }
    }
}
