//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarLeasePPT.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonBlock
    {
        public int PersonBlockId { get; set; }
        public int PersonId { get; set; }
        public System.DateTime EffectiveDateTime { get; set; }
        public System.DateTime ExpirationDateTime { get; set; }
        public bool IsOverridden { get; set; }
        public Nullable<int> OverriddenByPersonId { get; set; }
        public Nullable<System.DateTime> OverriddenOnDateTime { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Person PersonOverriddenBy { get; set; }
    }
}
