//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarLeasePPT.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonSecurity
    {
        public int PersonSecurityId { get; set; }
        public int PersonId { get; set; }
        public int PersonSecurityTypeId { get; set; }
        public string SecurityValue { get; set; }
        public System.DateTime EffectiveDateTime { get; set; }
        public System.DateTime ExpirationDateTime { get; set; }
        public int CreatedByPersonId { get; set; }
        public System.DateTime CreatedOnDateTime { get; set; }
        public Nullable<int> ModifiedByPersonId { get; set; }
        public Nullable<System.DateTime> ModifiedOnDateTime { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Person PersonCreatedBy { get; set; }
        public virtual Person PersonModifiedBy { get; set; }
    }
}
