//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarLeasePPT.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preference
    {
        public int PreferenceId { get; set; }
        public Nullable<int> PersonId { get; set; }
        public string PreferenceName { get; set; }
        public Nullable<int> ValueInt { get; set; }
        public Nullable<bool> ValueBool { get; set; }
        public Nullable<decimal> ValueDecimal { get; set; }
        public string ValueString { get; set; }
    }
}
