//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarLeasePPT.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxAssessor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaxAssessor()
        {
            this.Parcels = new HashSet<Parcel>();
            this.TaxCollectors = new HashSet<TaxCollector>();
        }
    
        public int TaxAssessorId { get; set; }
        public string TaxAssessorName { get; set; }
        public string StateAbbreviation { get; set; }
        public string County { get; set; }
        public Nullable<System.DateTime> AssessmentDate { get; set; }
        public Nullable<System.DateTime> TaxPeriodStart { get; set; }
        public Nullable<System.DateTime> TaxPeriodEnd { get; set; }
        public Nullable<int> CreatedByPersonId { get; set; }
        public Nullable<System.DateTime> CreatedOnDateTime { get; set; }
        public Nullable<int> ModifiedByPersonId { get; set; }
        public Nullable<System.DateTime> ModifiedOnDateTime { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeletedByPersonId { get; set; }
        public Nullable<System.DateTime> DeletedOnDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parcel> Parcels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaxCollector> TaxCollectors { get; set; }
        public virtual Person PersonCreatedBy { get; set; }
        public virtual Person PersonDeletedBy { get; set; }
        public virtual Person PersonModifiedBy { get; set; }
    }
}
