//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarLeasePPT.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxBill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaxBill()
        {
            this.ParcelTaxBills = new HashSet<ParcelTaxBill>();
            this.TaxBillCarLeases = new HashSet<TaxBillCarLease>();
            this.WorkItems = new HashSet<WorkItem>();
            this.TaxBillAttachments = new HashSet<TaxBillAttachment>();
        }
    
        public int TaxBillId { get; set; }
        public int TaxCollectorId { get; set; }
        public Nullable<int> TaxPaymentId { get; set; }
        public string BillNumber { get; set; }
        public string TaxYear { get; set; }
        public Nullable<System.DateTime> TaxPeriodStart { get; set; }
        public Nullable<System.DateTime> TaxPeriodEnd { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> DiscountDueDate { get; set; }
        public Nullable<System.DateTime> APExportDate { get; set; }
        public decimal TotalAmountOwed { get; set; }
        public decimal TotalTaxableValue { get; set; }
        public short MonthsTaxed { get; set; }
        public string CollectorAccountNumber { get; set; }
        public Nullable<int> RecordGroupId { get; set; }
        public Nullable<System.DateTime> DateComplete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParcelTaxBill> ParcelTaxBills { get; set; }
        public virtual TaxCollector TaxCollector { get; set; }
        public virtual TaxPayment TaxPayment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaxBillCarLease> TaxBillCarLeases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkItem> WorkItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaxBillAttachment> TaxBillAttachments { get; set; }
    }
}
