//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarLeasePPT.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxBillCarLease
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaxBillCarLease()
        {
            this.WorkItems = new HashSet<WorkItem>();
        }
    
        public int TaxBillCarLeaseId { get; set; }
        public int TaxBillId { get; set; }
        public Nullable<int> CarLeaseId { get; set; }
        public decimal BaseTax { get; set; }
        public decimal Discount { get; set; }
        public decimal PPTRACredit { get; set; }
        public decimal DecalRegistrationFee { get; set; }
        public decimal Penalty { get; set; }
        public decimal Interest { get; set; }
        public decimal TotalAmountOwed { get; set; }
        public decimal AssessedValue { get; set; }
        public decimal TaxableValue { get; set; }
        public string Vin { get; set; }
        public string PlateNumber { get; set; }
        public bool InterestIsBillable { get; set; }
        public bool PenaltyIsBillable { get; set; }
    
        public virtual TaxBill TaxBill { get; set; }
        public virtual CarLease CarLease { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkItem> WorkItems { get; set; }
    }
}
