//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarLeasePPT.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarLease
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarLease()
        {
            this.CustomerAddresses = new HashSet<CustomerAddress>();
            this.PhysicalAddresses = new HashSet<PhysicalAddress>();
            this.TaxBillCarLeases = new HashSet<TaxBillCarLease>();
            this.CarValuations = new HashSet<CarValuation>();
            this.WorkItems = new HashSet<WorkItem>();
            this.LeaseAttachments = new HashSet<LeaseAttachment>();
        }
    
        public int CarLeaseId { get; set; }
        public int CarMasterId { get; set; }
        public string LeaseNumber { get; set; }
        public string AssetNumber { get; set; }
        public string Vin { get; set; }
        public string LesseeFirstName { get; set; }
        public string LesseeLastName { get; set; }
        public int AssetStatusId { get; set; }
        public int LeaseStatusId { get; set; }
        public System.DateTime CommencementDate { get; set; }
        public System.DateTime ScheduledTerminationDate { get; set; }
        public Nullable<System.DateTime> ActualTerminationDate { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public string BranchCode { get; set; }
        public string CompanyCode { get; set; }
        public string ExemptionCode { get; set; }
        public string ProductUseCode { get; set; }
        public string TaxRecoveryCode { get; set; }
        public Nullable<decimal> OriginalCost { get; set; }
        public Nullable<decimal> SalesPrice { get; set; }
        public string RegistrationState { get; set; }
        public string PlateNumber { get; set; }
        public string PayoffSource { get; set; }
        public string TerminationCode { get; set; }
        public Nullable<System.DateTime> LastMoveDate { get; set; }
    
        public virtual AssetStatus AssetStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerAddress> CustomerAddresses { get; set; }
        public virtual LeaseStatus LeaseStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhysicalAddress> PhysicalAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaxBillCarLease> TaxBillCarLeases { get; set; }
        public virtual CarMaster CarMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarValuation> CarValuations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkItem> WorkItems { get; set; }
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaseAttachment> LeaseAttachments { get; set; }
    }
}
