//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarLeasePPT.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarValuation
    {
        public int CarValuationId { get; set; }
        public int CarLeaseId { get; set; }
        public string TaxYear { get; set; }
        public decimal CarValuationAmount { get; set; }
    
        public virtual CarLease CarLease { get; set; }
    }
}
