//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarLeasePPT.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkItem()
        {
            this.WorkItemActivities = new HashSet<WorkItemActivity>();
            this.WorkItemAttachments = new HashSet<WorkItemAttachment>();
        }
    
        public int WorkItemId { get; set; }
        public int WorkItemTypeId { get; set; }
        public int WorkItemStatusId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> TaxBillId { get; set; }
        public Nullable<int> CarLeaseId { get; set; }
        public Nullable<int> CarMasterId { get; set; }
        public Nullable<int> TaxCollectorId { get; set; }
        public string CompanyName { get; set; }
        public string GarageAddress { get; set; }
        public string GarageCity { get; set; }
        public string GarageCounty { get; set; }
        public string GarageState { get; set; }
        public bool IsUrgent { get; set; }
        public string LeaseNumber { get; set; }
        public string LesseeFirstName { get; set; }
        public string LesseeLastName { get; set; }
        public string Narrative { get; set; }
        public string PlateNumber { get; set; }
        public string TaxCollectorName { get; set; }
        public string TaxYear { get; set; }
        public string Vin { get; set; }
        public string CarMake { get; set; }
        public int CreatedByPersonId { get; set; }
        public System.DateTime CreatedOnDateTime { get; set; }
        public Nullable<int> ModifiedByPersonId { get; set; }
        public Nullable<System.DateTime> ModifiedOnDateTime { get; set; }
        public Nullable<System.DateTime> NoticeDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string NoticeNumber { get; set; }
        public string CompanyCode { get; set; }
        public Nullable<int> TaxBillCarLeaseId { get; set; }
    
        public virtual Person PersonCreatedBy { get; set; }
        public virtual Person PersonModifiedBy { get; set; }
        public virtual TaxBill TaxBill { get; set; }
        public virtual CarLease CarLease { get; set; }
        public virtual CarMaster CarMaster { get; set; }
        public virtual WorkItemStatus WorkItemStatus { get; set; }
        public virtual WorkItemType WorkItemType { get; set; }
        public virtual TaxCollector TaxCollector { get; set; }
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkItemActivity> WorkItemActivities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkItemAttachment> WorkItemAttachments { get; set; }
        public virtual TaxBillCarLease TaxBillCarLease { get; set; }
    }
}
