//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarLeasePPT.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkItemActivity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkItemActivity()
        {
            this.WorkItemAttachments = new HashSet<WorkItemAttachment>();
        }
    
        public int WorkItemActivityId { get; set; }
        public int WorkItemId { get; set; }
        public System.DateTime ActivityDateTime { get; set; }
        public int WorkItemActivityTypeId { get; set; }
        public string Narrative { get; set; }
        public bool IsPrivate { get; set; }
        public int CreatedByPersonId { get; set; }
        public System.DateTime CreatedOnDateTime { get; set; }
        public Nullable<System.DateTime> ModifiedOnDateTime { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeletedByPersonId { get; set; }
        public Nullable<System.DateTime> DeletedOnDateTime { get; set; }
    
        public virtual Person PersonCreatedBy { get; set; }
        public virtual Person PersonDeletedBy { get; set; }
        public virtual WorkItem WorkItem { get; set; }
        public virtual WorkItemActivityType WorkItemActivityType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkItemAttachment> WorkItemAttachments { get; set; }
    }
}
